version: '3.8'
services:
  app:
    tty: true
    command: yarn dev
    build:
      context: .
    ports:
      - 3000:3000
      - 5555:5555
    env_file:
      - .env
    volumes:
      - ./:/app
      - ch_node_modules:/app/node_modules
      - ch_next:/app/.next
      - ch_prisma:/app/.prisma
    depends_on:
      - db
    networks:
      - cyborghome_dev_network
  db:
    image: postgres:16.1-bullseye
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=blog
      - POSTGRES_USER=cyborg
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - cyborghome_dev_network
volumes:
  ch_node_modules:
  ch_next:
  ch_prisma:

networks:
  cyborghome_dev_network:
    driver: bridge
